image:
- Visual Studio 2017
environment:

  matrix:
  - PYTHON: "C:\\Python36-x64"

install:
- "set PATH=%PATH%;%PYTHON%\\Scripts"
- "%PYTHON%\\python.exe -m pip install --upgrade pip"
- "%PYTHON%\\python.exe -m pip install --upgrade setuptools"
- "%PYTHON%\\python.exe -m pip install --upgrade wheel"
- "git clone https://github.com/julienmalard/taqdir.git"
- ps: cd taqdir
- "%PYTHON%\\python.exe setup.py -q install"
- ps: cd ..
- "%PYTHON%\\python.exe -m pip install -r requ√≠sitos.txt"
- "%PYTHON%\\python.exe setup.py -q install"

build: false

test_script:
- "%PYTHON%\\python.exe -m unittest pruebas"